services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hookguard
      POSTGRES_USER: hookguard
      POSTGRES_PASSWORD: hookguard
    ports:
      - "5432:5432"
    volumes:
      - hookguard_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hookguard -d hookguard"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  hookguard_pg:
